#!/usr/bin/env bash
# Generate / scale N Dubbo press services.
#
#   - interfaces  -> dubbo-api-example      (package ...example.api.press)
#   - impls       -> dubbo-quickstart-provider (package ...provider.press)
#
# Padding is NOT generated as source. Edit PressMetadataPadding.DEFAULT_BYTES,
# or pass -Dpress.metadata.bytes / PRESS_METADATA_BYTES; PressMetadataInjector
# fills URL parameters at export time.
#
# Usage:
#   ./gen-press-services.sh gen <n>   generate exactly n services (scales up or down)
#   ./gen-press-services.sh count     show how many services are currently generated
#   ./gen-press-services.sh clean     remove generated PressService* sources only
#   ./gen-press-services.sh build     compile the two modules
#
# Env (runtime, not generation):
#   PRESS_METADATA_BYTES  padding size per service, default 525312 (512KB + 1KB)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXAMPLES_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${EXAMPLES_DIR}/.." && pwd)"

API_MODULE="dubbo-examples/dubbo-api-example"
PROVIDER_MODULE="dubbo-examples/dubbo-quickstart-example/dubbo-quickstart-provider"
API_PRESS_DIR="${REPO_ROOT}/${API_MODULE}/src/main/java/com/tencent/polaris/dubbo/example/api/press"
PROVIDER_PRESS_DIR="${REPO_ROOT}/${PROVIDER_MODULE}/src/main/java/com/tencent/polaris/dubbo/quickstart/example/provider/press"

API_PACKAGE="com.tencent.polaris.dubbo.example.api.press"
PROVIDER_PACKAGE="com.tencent.polaris.dubbo.quickstart.example.provider.press"

usage() {
  sed -n '2,19p' "$0"
  exit 1
}

license_header() {
  cat <<'EOF'
/*
 * Tencent is pleased to support the open source community by making dubbo-polaris-java available.
 *
 * Copyright (C) 2021 Tencent. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
EOF
}

service_name() {
  printf 'PressService%04d' "$1"
}

generate_interface() {
  local index name file
  index="$1"
  name="$(service_name "${index}")"
  file="${API_PRESS_DIR}/${name}.java"
  {
    license_header
    cat <<EOF

package ${API_PACKAGE};

/**
 * Generated by dubbo-examples/scripts/gen-press-services.sh - do not edit.
 */
public interface ${name} {

    String echo(String value);
}
EOF
  } >"${file}"
}

generate_impl() {
  local index name file
  index="$1"
  name="$(service_name "${index}")"
  file="${PROVIDER_PRESS_DIR}/${name}Impl.java"
  {
    license_header
    cat <<EOF

package ${PROVIDER_PACKAGE};

import ${API_PACKAGE}.${name};
import org.apache.dubbo.config.annotation.DubboService;
import org.apache.dubbo.rpc.RpcContext;

/**
 * Generated by dubbo-examples/scripts/gen-press-services.sh - do not edit.
 * Metadata padding is injected at export by PressMetadataInjector.
 */
@DubboService(parameters = {
        "press.meta.index", "${index}"
})
public class ${name}Impl implements ${name} {

    @Override
    public String echo(String value) {
        return "${name}: " + value + " (provider port: " + RpcContext.getContext().getLocalPort() + ")";
    }
}
EOF
  } >"${file}"
}

current_count() {
  local count
  count=$(find "${API_PRESS_DIR}" -maxdepth 1 -name 'PressService*.java' 2>/dev/null | wc -l | tr -d ' ')
  echo "${count:-0}"
}

do_gen() {
  local target i name
  target="${1:-}"
  if [[ -z "${target}" || ! "${target}" =~ ^[0-9]+$ ]]; then
    echo "gen requires a non-negative service count" >&2
    exit 1
  fi
  if [[ "${target}" -eq 0 ]]; then
    do_clean
    return
  fi

  mkdir -p "${API_PRESS_DIR}" "${PROVIDER_PRESS_DIR}"

  for file in "${API_PRESS_DIR}"/PressService*.java; do
    [[ -e "${file}" ]] || continue
    name="$(basename "${file}" .java)"
    i=$((10#${name#PressService}))
    if [[ "${i}" -gt "${target}" ]]; then
      rm -f "${file}" "${PROVIDER_PRESS_DIR}/${name}Impl.java"
    fi
  done

  for ((i = 1; i <= target; i++)); do
    generate_interface "${i}"
    generate_impl "${i}"
  done

  echo "generated ${target} press services"
  echo "  interfaces: ${API_PRESS_DIR}"
  echo "  impls     : ${PROVIDER_PRESS_DIR}"
  echo "  padding   : edit PressMetadataPadding.DEFAULT_BYTES or set PRESS_METADATA_BYTES"
}

do_clean() {
  rm -f "${API_PRESS_DIR}"/PressService*.java "${PROVIDER_PRESS_DIR}"/PressService*Impl.java
  if [[ -d "${PROVIDER_PRESS_DIR}" ]] && [[ -z "$(ls -A "${PROVIDER_PRESS_DIR}" 2>/dev/null || true)" ]]; then
    rmdir "${PROVIDER_PRESS_DIR}"
  fi
  echo "cleaned generated PressService* sources (PressMetadataPadding kept)"
}

do_build() {
  (cd "${REPO_ROOT}" && mvn -q -pl "${PROVIDER_MODULE}" -am package -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip=true)
  echo "build ok"
}

case "${1:-}" in
  gen)
    do_gen "${2:-}"
    ;;
  count)
    echo "$(current_count) press services generated"
    ;;
  clean)
    do_clean
    ;;
  build)
    do_build
    ;;
  *)
    usage
    ;;
esac
